export const CARD_INFO_TRAINING_PHRASES = [
	`{{MONSTER}}`,
	`{{questionType}} can i {{actionType}} {{MONSTER}}`,
	`{{questionType}} can i use to {{actionType}} {{MONSTER}}`,
	`{{questionType}} are the {{infoType}} of {{MONSTER}},`,
	`{{infoType}} for {{MONSTER}}`,
	`{{questionType}} {{infoType}} can i find {{MONSTER}}`,
	`{{questionType}} {{infoType}} is she from`,
	`{{infoType}} {{MONSTER}}`,
	`{{MONSTER}} {{infoType}}`,
	`i want to know more about {{MONSTER}}`,
	`{{questionType}} is {{MONSTER}} {{infoType}}`,
	`{{questionType}} is {{MONSTER}}'s {{infoType}}`,
	`{{questionType}} about {{MONSTER}} {{infoType}}`,
	`{{questionType}} about {{MONSTER}}'s {{infoType}}`,
	`tell me about {{MONSTER}}`,
	`show me a {{infoType}} of {{MONSTER}}`,
	`{{questionType}} {{MONSTER}} {{infoType}}`,
	`{{questionType}} should we {{actionType}} {{MONSTER}}`,
	`show me {{MONSTER}}`,
	`{{questionType}} {{infoType}} is {{MONSTER}}`,
	`is {{MONSTER}} {{actionType}}`,
	`can {{MONSTER}} be {{actionType}}`,
	`how much is {{MONSTER}} {{actionType}} for`,
	`i want to {{actionType}} {{MONSTER}}`,
	`how much can I {{actionType}} {{MONSTER}} for`,
	`how {{infoType}} is {{MONSTER}}`,
	`{{questionType}} is {{MONSTER}}`,
	`{{questionType}}'s the {{infoType}} for {{MONSTER}}`,
	`does {{MONSTER}} have {{infoType}}`,
	`can I {{actionType}} {{MONSTER}}`,
];
