export const CARD_QUERY_TRAINING_PHRASES = [
	`{{monsterName:shelling_ford}} {{queryEvoType:equip:assist:weapon}}`,
	`{{monsterAttribute1:red}} {{monsterName:shelling_ford}} {{queryEvoType:equip:assist:weapon}}`,
	`{{monsterAttribute1:green}} {{monsterName:shelling_ford}} {{queryEvoType:equip:assist:weapon}}`,
	`{{monsterAttribute1:light}} {{monsterName:shelling_ford}} {{queryEvoType:equip:assist:weapon}}`,
	`{{monsterName:shelling_ford}} {{queryEvoType:equip:assist:weapon}}`,
	`{{monsterSeries}} series`,
	`{{monsterSeries}} collab`,
	`{{targetObject}} from {{monsterSeries}} collab`,
	`{{targetObject}} from {{monsterSeries}} series`,

	`{{ATTRIBUTES}} {{monsterTypes}} {{MONSTER}} {{queryEvoType}}`,
	`{{ATTRIBUTES}} {{MONSTERQUERYTYPE}} of {{MONSTER}}`,
	`{{ATTRIBUTES}} {{monsterTypes}} {{targetObject}} from {{monsterSeries}}`,
	`{{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} from {{monsterSeries}}`,
	`{{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} from {{monsterSeries}} series`,
	`show me all {{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} with {{FILTERS}} from {{monsterSeries}} collab`,
	`list all {{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} with {{FILTERS}} from {{monsterSeries}} series`,
	`I want a list of all {{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} with {{FILTERS}} from {{monsterSeries}} collab`,
	`What are the {{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} that have {{FILTERS}} from bleach series`,
	`Find me all {{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} with {{FILTERS}} from {{monsterSeries}} collab`,
	`Show me a list of {{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} that have {{FILTERS}} from {{monsterSeries}} series`,
	`Search for all {{ATTRIBUTES}} {{MONSTERQUERYTYPE}} with {{FILTERS}} from {{monsterSeries}} collab`,
	`Help me find all {{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} with {{FILTERS}} from {{monsterSeries}} collab`,
	`Search {{monsterSeries}} series for all {{ATTRIBUTES}} {{MONSTERQUERYTYPE}} {{targetObject}} that have {{FILTERS}}`,
];
