export const MANUAL_LIST = {
	1790: ['chibi haku', 'mini haku'],
	1788: ['chibi meimei', 'mini mei mei'],
	1714: ['chibi green zhuge liang', 'chibi gzl', 'mini green zhuge liang', 'mini gzl'],
	2023: ['chibi isis', 'mini isis'],
	141: ['tsukuyomi'], //To overwrite Yomi and Tsukuyomi > Yomi
	2908: ['chibi verdandi', 'mini verdandi'],
	1785: ['chibi valkyrie', 'chibi light valkyrie', 'mini valkyrie', 'mini light valkyrie'],
	1877: ['evo chibi zhao yun', 'evo mini zhao yun'],
	3097: ['chibi sylvie', 'mini sylvie'],
	3100: ['chibi sonia gran', 'mini sonia gran'],
	1856: ['Ken-Oh, Raoh'],
	1794: ['chibi seraph lucifer', 'mini seraph lucifer'],
	2912: ['chibi bastet', 'chibi awoken bastet', 'mini bastet', 'mini awoken bastet'],
	3252: ['chibi archdemon lucifer', 'mini archdemon lucifer'],
	2907: ['chibi urd', 'mini urd'],
	2909: ['chibi skuld', 'mini skuld'],
	2911: ['chibi awoken isis', 'mini awoken isis'],
	1822: ['evo chibi red guan yu', 'evo chibi rgy', 'evo mini red guan yu', 'evo mini rgy'],
	1818: ['evo chibi da qiao & xiao quiao', 'evo mini da quiao & xiao quiao', 'evo chibi dqxq', 'evo mini dqxq'],
	6196: ['3000 days aniversary tamadra'],
	1717: ['evo chibi green guan yu', 'evo chibi ggy', 'evo mini green guan yu', 'evo mini ggy'],
	1792: ['chibi metatron', 'mini metatron'],
	989: ['chibi tsukuyomi', 'mini tsukuyomi', 'chibi yomi', 'mini yomi'],
	3830: ['2000 days aniversary tamadra'],
	2022: ['chibi amaterasu', 'mini amaterasu', 'chibi ama', 'mini ama'],
	1813: ['chibi sun quan', 'chibi sunquan', 'mini sun quan', 'mini sunquan'],
	1814: ['evo chibi sun quan', 'evo chibi sunquan', 'evo mini sun quan', 'evo mini sunquan'],
	1820: ['evo chibi lu bu', 'evo chibi lubu', 'evo mini lu bu', 'evo mini lubu'],
	1715: ['evo chibi zhuge liang', 'mini green evo liang'],
	2020: ['chibi chiyome', 'mini chiyome'],
	1811: [
		'chibi cao cao',
		'chibi caocao',
		'chibi base cao cao',
		'chibi base caocao',
		'mini cao cao',
		'mini caocao',
		'mini base cao cao',
		'mini base caocao',
	],
	1812: ['evo chibi cao cao', 'evo chibi caocao', 'evo mini cao cao', 'evo mini caocao'],
	2315: ['chibi hera', 'mini hera'],
	2207: ['hp latent tamadra'],
	2208: ['atk latent tamadra'],
	2209: ['rcv latent tamadra'],
	2210: ['auto-rcv latent tamadra'],
	2211: ['te latent tamadra'],
	2212: ['fire damage reduction latent tamadra'],
	2213: ['water damage reduction latent tamadra'],
	2214: ['wood damage reduction latent tamadra'],
	2215: ['light damage reduction latent tamadra'],
	2216: ['dark damage reduction latent tamadra'],
	2425: ['latent tamadra skill delay resist', 'sdr'],
	3317: ['all stats tatamdra'],
	3318: ['god killer tatamdra'],
	3319: ['dragon killer tatamdra'],
	3320: ['devil killer tatamdra'],
	3321: ['machine killer tatamdra'],
	3322: ['balanced killer tatamdra'],
	3323: ['attacker killer tatamdra'],
	3324: ['physical killer tatamdra'],
	3325: ['healer killer tatamdra'],
	3700: ['hp+ latent tamdadra'],
	3701: ['atk+ latent tamdadra'],
	3702: ['rcv+ latent tamdadra'],
	3703: ['te+ latent tamdadra'],
	3717: ['evo mataterial killer tamadra', 'evo mat killer tamadra'],
	3718: ['awoken material killer tamadra', 'awoken mat killer tamadra'],
	3719: ['enhanced material killer tamadra', 'enhanced mat killer tamadra'],
	3720: ['redeemable material killer tamadra', 'redeemable mat killer tamadra'],
	4369: ['fire damage reduction + latent tamadra'],
	4370: ['water damage reduction + latent tamadra'],
	4371: ['wood damage reduction + latent tamadra'],
	4372: ['light damage reduction + latent tamadra'],
	4373: ['dark damage reduction + latent tamadra'],
	5739: ['extra slot tamadra'],
	6073: ['leader swap resist tamadra', 'leader swap tamadra'],
	6074: ['jammer surge resist tamadra', 'jammer resist tamadra', 'jammer tamadra'],
	6075: ['poison surge resist tamadra', 'poison resist tamadra', 'poison tamadra'],
	6076: [
		'damage void piercer tamadra',
		'damage void pierce tamadra',
		'damage void piercing tamadra',
		'damage void tamadra',
		'dvp tamadra',
		'vdp tamadra',
	],
	6077: ['att. absorption piercer tamadra', 'attribute absoption piercer tamadra', 'attribute void tamadra'],
	1791: ['evo chibi tsukuyomi', 'evo chibi yomi', 'evo mini tsukuyomi', 'evo mini yomi'],
	2314: ['chibi hera-ur', 'chibi heraur', 'chibi hera ur', 'mini hera-ur', 'mini heraur', 'mini hera ur'],
	2317: ['evo chibi red sonia', 'evo chibi ronia', 'evo mini red sonia', 'evo mini ronia'],
	2025: ['chibi andromeda', 'chibi andro', 'mini andromeda', 'mini andro'],
	1789: ['evo chibi sakuya', 'evo mini sakuya', 'chibi sakuya', 'mini sakuya'],
	2027: ['chibi sun wukong', 'mini sun wukong'],
	2914: ['chibi awoken tsukuyomi', 'chibi awoken yomi', 'mini awoken tsukuyomi', 'mini awoken yomi'],
	2906: ['chibi dark valkyrie', 'mini dark valkyrie'],
	2110: ['gungho vampire', 'gh vampire'],
	3099: ['chibi light kali', 'mini light kali'],
	2026: ['chibi perseus', 'mini perseus'],
	2021: ['chibi red odin', 'chibi rodin', 'mini red odin', 'mini rodin'],
	1821: ['chibi red guan yu', 'chibi rgy', 'mini red guan yu', 'mini rgy'],
	1816: ['evo chibi liu bei', 'evo chibi lb', 'evo mini liu bei', 'evo chibi lb'],
	1819: ['chibi lu bu', 'chibi lubu', 'mini lu bu', 'mini lubu'],
	1786: ['chibi leilan', 'mini leilan'],
	2910: ['evo chibi pandora', 'evo mini pandora'],
	2028: ['chibi pandora', 'mini pandora'],
	2316: ['evo chibi metatron', 'evo mini metatron'],
	3096: ['chibi ryune', 'mini ryune'],
	1824: ['evo chibi light zhuge liang', 'evo chibi lzl', 'evo mini light zhuge liang', 'evo chibi lzl'],
	1716: ['chibi green guan yu', 'chibi ggy', 'mini green guan yu', 'mini ggy'],
	3098: ['chibi saria', 'mini saria'],
	1817: ['chibi da qiao & xiao quiao', 'mini da quiao & xiao quiao', 'chibi dqxq', 'mini dqxq'],
	2024: ['chibi yamato takeru', 'chibi yamato', 'mini yamato takeru', 'mini yamato'],
	1876: ['chibi zhao yun', 'mini zhao yun'],
	1815: ['chibi liu bei', 'chibi lb', 'mini liu bei', 'chibi lb'],
	1793: ['chibi red sonia', 'chibi ronia', 'mini red sonia', 'mini ronia'],
	1823: ['chibi light zhuge liang', 'chibi lzl', 'mini light zhuge liang', 'chibi lzl'],
	2321: ['evo chibi valkyrie', 'evo chibi light valkyrie', 'evo mini valkyrie', 'evo mini light valkyrie'],
	1784: ['chibi lilith', 'mini lilith'],
	1857: ['evo farmable raoh'],
	2825: [
		'ultimate evo wonder woman film',
		'utilmate evo wonder woman',
		'uevo wonder woman film',
		'uevo wonder woman',
	],
	5124: ['wonder woman film'],
	2135: ['harley quinn'],
	1689: ['harley quinn comic'],
	4804: [
		'dbdc omega',
		'green omega',
		'green red omega',
		'wood omega',
		'dragonbound omega',
		'dragoncaller omega',
		'dragon caller omega',
	],
	4805: [
		'evo dbdc omega',
		'evo green omega',
		'evo green red omega',
		'evo wood omega',
		'evo dragonbound omega',
		'evo dragoncaller omega',
		'evo dragon caller omega',
	],
	1787: ['chibi karin', 'mini karin'],
	6163: ['dazzling beast goddess, tsukuyomi dark color', 'tsukuyomi dark color', 'yomi dark color'],
	2057: ['final fantasy gilgamesh', 'ff gilgamesh', 'fire water gilgamesh'],
	5009: ['fate gilgamesh', 'stay night gilgamesh', 'hf gilgamesh', 'light dark gilgamesh'],
	5643: ['goury'],
	5644: ['evo goury'],
	2261: ['evo yomi dragon', 'evo tsukuyomi dragon'],
};
