export const MONSTER_TYPES = {
	'-1': 'None',
	0: 'Evo Material',
	1: 'Balanced',
	2: 'Physical',
	3: 'Healer',
	4: 'Dragon',
	5: 'God',
	6: 'Attacker',
	7: 'Devil',
	8: 'Machine',
	12: 'Awaken Material',
	14: 'Enhance Material',
	15: 'Redeemable Material',
};
