export const MONSTER_COLLABS = {
	0: 'None',
	1: 'RO',
	2: 'Taiko',
	3: 'ECO',
	4: 'Plan and Brood',
	5: 'Gunma',
	6: 'FFCD',
	7: 'Famitsu (Necky)',
	8: 'Punt',
	9: 'Puzzdroid',
	10: 'Shinra',
	11: 'Kapybara',
	12: 'Cathy. (Only has Cathy and her evo.)',
	13: '(Ukai Magoroku and its evo.)',
	14: 'Eva.',
	15: '7-11 Collab',
	16: 'Clash of Clans',
	17: 'Groove Coaster.',
	18: 'RO ACE.',
	19: "Dragon's Dogma Quest",
	20: 'Takaoka',
	21: 'Monster Hunter',
	22: 'Batman',
	23: 'Baskin Robbins',
	24: 'Angry Birds.',
	25: 'PAD Z',
	26: 'HxH',
	27: 'Hello Kitty.',
	28: 'PAD BT',
	29: 'BEAMS',
	30: 'Dragon Ball',
	31: 'Saint Seiya',
	32: 'GungHo Collab (Spirit)',
	33: "GungHo Collab (King's Gate?)",
	34: 'GungHo Collab (Unknown Game)',
	35: 'GungHo Collab (Unknown Game)',
	36: 'Bikkuriman',
	37: 'Angry Birds E-something',
	38: 'DC',
	39: 'Sangoku Tenka Trigger',
	40: 'Fist of the North Stars',
	41: 'Chibis',
	42: 'Diagoldos',
	43: 'Unknown',
	44: 'Chibis #2',
	45: 'FF',
	46: 'GitS',
	47: 'Duel Masters',
	48: 'Attack on Titan',
	49: 'Ninja Hattori-Kun',
	50: 'Shonen Sunday',
	51: 'Crows X Worst',
	52: 'Bleach',
	53: 'Superman vs Batman',
	54: 'PAD X',
	55: 'Ace Attorney',
	89: 'Yugioh! Duel Monsters',
};
