export const MONSTER_COLLABS = {
	0: { name: 'None', group: null, aliases: [] },
	1: { name: 'RO', group: null, aliases: [] },
	2: { name: 'Taiko no Tatsujin', group: null, aliases: ['taiko', 'don chan', 'donchan'] },
	3: { name: 'ECO', group: null, aliases: [] },
	4: { name: 'Plan and Brood', group: null, aliases: [] },
	5: { name: 'Gunma', group: null, aliases: [] },
	6: { name: 'Crystal Defender', group: null, aliases: ['ffcd', 'defender'] },
	7: { name: 'Famitsu', group: null, aliases: [] },
	8: { name: 'Punt', group: null, aliases: ['princess punt'] },
	9: { name: 'Puzzdroid', group: null, aliases: [] },
	10: { name: 'Shinrabansho', group: null, aliases: ['shinra', 'shinrabansho choco', 'choco'] },
	11: { name: 'Kapibara-San', group: null, aliases: ['kapybara', 'kapibara', 'kapibara san'] },
	12: { name: 'Cathy', group: null, aliases: [] },
	//13: Unknown
	14: { name: 'Evagelion', group: null, aliases: ['eva', 'evangelion'] },
	15: { name: '7-11', group: null, aliases: ['711'] },
	16: { name: 'Clash of Clans', group: null, aliases: ['coc'] },
	17: { name: 'Groove Coaster', group: null, aliases: [] },
	18: { name: 'RO ACE', group: null, aliases: [] },
	19: { name: "Dragon's Dogma Quest", group: null, aliases: [] },
	20: { name: 'Takaoka City', group: null, aliases: ['takaoka'] },
	21: {
		name: 'Monster Hunter 4G',
		group: 'monsterHunter',
		aliases: ['mh 4g'],
	},
	22: { name: 'Batman', group: null, aliases: ['bat man'] },
	23: { name: 'Baskin Robbins', group: null, aliases: ['br'] },
	24: { name: 'Angry Birds', group: null, aliases: [] },
	25: { name: 'PAD Z', group: null, aliases: ['padz'] },
	26: { name: 'Hunter x Hunter', group: null, aliases: ['hunterxhunter', 'hxh', 'hunter cross hunter'] },
	27: { name: 'Sanrio', group: null, aliases: ['hk', 'kitty', 'hello kitty'] },
	28: {
		name: 'PAD Battle Tournament',
		group: null,
		aliases: ['pad bt', 'padbattle', 'battle tournament', 'pad battle'],
	},
	29: { name: 'BEAMS', group: null, aliases: ['pad bear', 'ilovepad', 'iluvpad', 'i love pad', 'i luv pad'] },
	30: { name: 'Dragon Ball', group: null, aliases: ['dbz', 'db'] },
	31: { name: 'Saint Seiya', group: null, aliases: ['seiya', 'saint saiya', 'saiya', 'st seiya', 'st saiya'] },
	32: { name: 'GungHo Collab (Spirit)', group: 'gungho', aliases: [] },
	33: { name: "GungHo Collab (King's Gate)", group: 'gungho', aliases: [] },
	34: { name: 'GungHo Collab (Unknown Game)', group: 'gungho', aliases: [] },
	35: { name: 'GungHo Collab (Unknown Game)', group: 'gungho', aliases: [] },
	36: { name: 'Bikkuriman', group: null, aliases: [] },
	37: { name: 'Angry Birds', group: null, aliases: [] },
	38: { name: 'DC', group: 'dc', aliases: ['dc comics'] },
	39: { name: 'Sangoku Tenka Trigger', group: null, aliases: ['chibi 3k'] },
	40: { name: 'Fist of the North Stars', group: null, aliases: ['fotns', 'fist', 'north star'] },
	41: { name: 'Chibi', group: 'chibi', aliases: ['mini'] },
	42: { name: 'Diagoldos', group: null, aliases: [] },
	// 43: Unknown
	44: { name: 'Chibi 2', group: 'chibi', aliases: ['mini 2'] },
	45: { name: 'Final Fantasy', group: null, aliases: ['ff'] },
	46: { name: 'Ghost in the Shell', group: null, aliases: ['gits', 'rojikoma', 'newport'] },
	47: { name: 'Duel Masters', group: null, aliases: ['dm'] },
	48: { name: 'Attack on Titan', group: null, aliases: ['aot', 'titan'] },
	49: {
		name: 'Ninja Hattori-Kun',
		group: null,
		aliases: ['ninja hattori', 'fujio', 'hattori', 'hattori-kun', 'hattori kun'],
	},
	50: { name: 'Shonen Sunday', group: null, aliases: ['sunday', 'shonen', 'jump'] },
	51: { name: 'Crows X Worst', group: null, aliases: ['crows', 'crow'] },
	52: { name: 'Bleach', group: null, aliases: [] },
	53: { name: 'Superman vs Batman', group: 'dc', aliases: ['batman vs superman', 'dc'] },
	54: { name: 'PAD X', group: null, aliases: ['padx'] },
	55: { name: 'Ace Attorney', group: null, aliases: [] },
	56: { name: 'Rurouni Kenshin', group: null, aliases: ['kenshin'] },
	57: { name: 'Pepper', group: null, aliases: ['peper'] },
	58: { name: 'Kinnikuman', group: null, aliases: [] },
	59: { name: 'Morikawa', group: null, aliases: ['kokone morikawa'] },
	60: { name: 'Magazine All Stars', group: null, aliases: ['magazine', 'all stars', 'allstars'] },
	61: { name: 'Monster Hunter 2', group: 'monsterHunter', aliases: ['mh 2', 'monhun 2', 'mon hun 2', 'mh2'] },
	// 62: Unknown
	63: { name: 'Voltron', group: null, aliases: [] },
	//64: Unknown
	65: {
		name: 'Fullmetal Alchemist',
		group: null,
		aliases: ['fma', 'full metal', 'fullmetal', 'full metal alchemist'],
	},
	66: { name: 'King of Fighters', group: null, aliases: ['kof'] },
	67: { name: 'Yu Yu Hakusho', group: null, aliases: ['yyh', 'yusuke', 'yuyu'] },
	68: { name: 'Persona', group: null, aliases: [] },
	69: { name: 'Coca-Cola', group: null, aliases: ['cocacola', 'coke', 'coca cola', 'cola'] },
	70: { name: 'Magic the Gathering', group: null, aliases: ['magic', 'magic cards', 'mtg'] },
	71: { name: 'Gungho (REM)', group: 'gungho', aliases: ['gh'] },
	72: { name: 'Gungho (4720)', group: 'gungho', aliases: [] },
	73: { name: 'Gungho (4721)', group: 'gungho', aliases: [] },
	74: { name: 'Power Pros', group: null, aliases: ['powerpro', 'powerpros', 'power pro', 'baseball'] },
	75: { name: 'Gintama', group: null, aliases: [] },
	76: { name: 'Sword Art Online', group: null, aliases: ['sao', 'sword art'] },
	77: { name: 'Kamen Rider', group: null, aliases: ['rider', 'kamen', 'kr', 'kamen riders'] },
	78: {
		name: 'Power Rangers',
		group: 'yokai_pr',
		aliases: ['power rangers', 'pr', 'mmpr'],
	},
	79: {
		name: 'Fate',
		group: null,
		aliases: [
			'fate/stay night',
			'fate stay',
			'hf',
			'heaven feels',
			'fsn',
			"heaven's feel",
			'heavens feel',
			'fhf',
			'fate stay night',
			'stay night',
		],
	},
	//80: Unknown
	81: {
		name: 'Street Fighter V',
		group: null,
		aliases: ['streetfighter', 'sf', 'sfv', 'street fighter', 'sf5', 'street fighter 5'],
	},
	82: { name: "McDonald's", group: null, aliases: ['mdc', 'mccotton', 'mcdonalds', 'mc donald'] },
	83: { name: 'Shaman King', group: null, aliases: ['sk', 'shaman'] },
	84: { name: 'Shonen Champion', group: null, aliases: ['champion', 'champions'] },
	85: { name: 'Samurai Shodown', group: null, aliases: ['samurai showdown', 'samsho', 'samurai spirits', 'samurai'] },
	86: { name: 'Power Ranger 2', group: 'yokai_pr', aliases: ['pr 2'] },
	87: { name: 'Fujimi Fantasia', group: null, aliases: ['fantasia', 'fujimi'] },
	88: { name: 'Shinkalion', group: null, aliases: ['train', 'trains', 'shinkalion train', 'shinkalion trains'] },
	89: { name: 'Yugioh! Duel Monsters', group: null, aliases: ['yugioh', 'ygo', 'yugi'] },
	90: {
		name: 'Mickey & Friends',
		group: null,
		aliases: ['mickey mouse', 'disney', 'mickeys and friends', 'mnf', 'mickey', 'mickey&friends', 'm&f'],
	},

	91: {
		name: 'Devil May Cry V',
		group: null,
		aliases: ['dmv', 'wallet may cry', 'dmc', 'dmcv', 'devil may cry', 'Devil May Cry 5'],
	},
	92: {
		name: 'My Hero Academia',
		group: null,
		aliases: ['mha', 'my hero', 'mero academia', 'mero', 'boku no hero', 'boku no hero academia', 'bnh', 'bnha'],
	},
};
